# Basic
Region: noset
ImageID: noset
InstanceType: noset
InstanceyQty: noset

# IAM
IAMRole: noset
KeyName: noset

# Networking
vpc_id: noset
subnet_id: noset
public_ip: noset
placement_group: noset
InstanceSecurityGroup:
  - noset

# Storage
block_storage:
  - noset

# Labels
tags:
  - noset

# UserData
userdata: |
  sudo apt install -y nginx
